Repository AY2223S1-CS2103T-F11-2/tp, pull requests merged in 2022-11, with the labels that each got.

#253 Fix bug regarding integer overflow
  src/main/java/seedu/address/logic/parser/DeleteTagCommandParser.java
  src/main/java/seedu/address/logic/parser/EditTagCommandParser.java
  src/main/java/seedu/address/logic/parser/ParserUtil.java
Labels: bug

#256 Fix bug where main list does not appear
  src/main/java/seedu/address/logic/commands/AddModuleCommand.java
Labels: bug

#252 Add tests for all tag commands and tags
  src/main/java/seedu/address/logic/commands/AddTagCommand.java
  src/main/java/seedu/address/logic/commands/DeleteTagCommand.java
  src/main/java/seedu/address/logic/commands/EditTagCommand.java
  src/main/java/seedu/address/logic/parser/AddTagCommandParser.java
  src/main/java/seedu/address/logic/parser/CliSyntax.java
  src/main/java/seedu/address/logic/parser/DeleteTagCommandParser.java
  src/main/java/seedu/address/logic/parser/EditTagCommandParser.java
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/main/java/seedu/address/model/tag/DeadlineTag.java
  src/main/java/seedu/address/model/tag/PriorityTag.java
  src/main/java/seedu/address/model/tag/exceptions/BothTagsCannotBeNullException.java
  src/main/java/seedu/address/storage/JsonAdaptedTask.java
  src/test/java/seedu/address/logic/commands/AddTagCommandTest.java
  src/test/java/seedu/address/logic/commands/DeleteTagCommandTest.java
  src/test/java/seedu/address/logic/commands/EditTagCommandTest.java
  src/test/java/seedu/address/logic/commands/ExitCommandTest.java
  src/test/java/seedu/address/logic/commands/HelpCommandTest.java
  src/test/java/seedu/address/logic/parser/AddTagCommandParserTest.java
  src/test/java/seedu/address/logic/parser/DeleteTagCommandParserTest.java
  src/test/java/seedu/address/logic/parser/EditTagCommandParserTest.java
  src/test/java/seedu/address/model/tag/DeadlineTagTest.java
  src/test/java/seedu/address/model/tag/PriorityTagTest.java
  src/test/java/seedu/address/model/tag/TagTest.java
  src/test/java/seedu/address/testutil/DeadlineTagBuilder.java
  src/test/java/seedu/address/testutil/PriorityTagBuilder.java
  src/test/java/seedu/address/testutil/TaskBuilder.java
  src/test/java/seedu/address/testutil/TypicalIndexes.java
  src/test/java/seedu/address/testutil/TypicalTasks.java
Labels: priority.High, type.Task

#266 Add tests for ClearTasksCommand and ClearAllCommand classes
  src/test/java/seedu/address/logic/commands/ClearAllCommandTest.java
  src/test/java/seedu/address/logic/commands/ClearTasksCommandTest.java
Labels: type.Task

#269 Add tests for ListExamTasksCommand and ListExamTasksCommandParser classes
  src/main/java/seedu/address/logic/parser/ListExamTasksCommandParser.java
  src/test/java/seedu/address/logic/commands/ListExamTasksCommandTest.java
  src/test/java/seedu/address/logic/parser/ListExamTasksCommandParserTest.java
  src/test/java/seedu/address/testutil/TypicalIndexes.java
Labels: type.Task

#267 Amend bug for edit module feature
  src/main/java/seedu/address/model/AddressBook.java
  src/main/java/seedu/address/model/exam/DistinctExamList.java
  src/main/java/seedu/address/model/exam/Exam.java
  src/main/java/seedu/address/model/module/Module.java
  src/main/java/seedu/address/model/task/DistinctTaskList.java
  src/main/java/seedu/address/model/task/Task.java
  src/test/java/seedu/address/model/task/TaskTest.java
Labels: bug, priority.High

#270 Add tests for ParserUtil
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/main/java/seedu/address/model/commons/Criteria.java
  src/test/java/seedu/address/logic/parser/ParserUtilTest.java
Labels: type.Task

#287 Edit PPP
  docs/team/sampy147.md
Labels: documentation

#284 Update PPP
  docs/team/phualiting.md
Labels: documentation

#286 Update ppp
  docs/team/dlimyy.md
Labels: documentation

#288 Update PPP
  docs/team/tlx02.md
Labels: documentation

#279 Add tests for UnlinkExamCommand and UnlinkExamCommandParser classes
  src/test/java/seedu/address/logic/commands/UnlinkExamCommandTest.java
  src/test/java/seedu/address/logic/parser/UnlinkExamCommandParserTest.java
  src/test/java/seedu/address/testutil/TaskBuilder.java
  src/test/java/seedu/address/testutil/TypicalIndexes.java
Labels: type.Task

#268 Add tests for DeleteExamCommand and DeleteExamCommandParser classes
  src/main/java/seedu/address/logic/parser/DeleteExamCommandParser.java
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/logic/commands/DeleteExamCommandTest.java
  src/test/java/seedu/address/logic/parser/AddTaskCommandParserTest.java
  src/test/java/seedu/address/logic/parser/DeleteExamCommandParserTest.java
  src/test/java/seedu/address/testutil/TypicalTasks.java
Labels: type.Task

#257 Add tests for various classes
  src/main/java/seedu/address/logic/commands/LinkExamCommand.java
  src/main/java/seedu/address/logic/commands/SortTaskCommand.java
  src/main/java/seedu/address/logic/parser/AddModuleCommandParser.java
  src/main/java/seedu/address/logic/parser/DeleteTagCommandParser.java
  src/main/java/seedu/address/logic/parser/EditTagCommandParser.java
  src/main/java/seedu/address/logic/parser/LinkExamCommandParser.java
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/main/java/seedu/address/logic/parser/SortTaskCommandParser.java
  src/main/java/seedu/address/model/AddressBook.java
  src/main/java/seedu/address/model/Criteria.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/model/module/Module.java
  src/main/java/seedu/address/model/module/ModuleCode.java
  src/main/java/seedu/address/model/task/DistinctTaskList.java
  src/main/java/seedu/address/model/task/Task.java
  src/test/java/seedu/address/logic/commands/AddCommandTest.java
  src/test/java/seedu/address/logic/commands/AddExamCommandTest.java
  src/test/java/seedu/address/logic/commands/AddModuleCommandIntegrationTest.java
  src/test/java/seedu/address/logic/commands/AddModuleCommandTest.java
  src/test/java/seedu/address/logic/commands/AddTaskCommandTest.java
  src/test/java/seedu/address/logic/commands/LinkExamCommandTest.java
  src/test/java/seedu/address/logic/commands/SortTaskCommandTest.java
  src/test/java/seedu/address/logic/parser/AddCommandParserTest.java
  src/test/java/seedu/address/logic/parser/AddModuleCommandParserTest.java
  src/test/java/seedu/address/logic/parser/LinkExamCommandParserTest.java
  src/test/java/seedu/address/logic/parser/ParserUtilTest.java
  src/test/java/seedu/address/logic/parser/SortTaskCommandParserTest.java
  src/test/java/seedu/address/model/CriteriaTest.java
  src/test/java/seedu/address/model/ModelManagerTest.java
  src/test/java/seedu/address/model/module/DistinctModuleListTest.java
  src/test/java/seedu/address/model/module/ModuleCodeTest.java
  src/test/java/seedu/address/model/module/ModuleTest.java
  src/test/java/seedu/address/model/task/TaskTest.java
  src/test/java/seedu/address/storage/StorageManagerTest.java
  src/test/java/seedu/address/testutil/CriteriaBuilder.java
  src/test/java/seedu/address/testutil/TypicalExams.java
  src/test/java/seedu/address/testutil/TypicalIndexes.java
Labels: type.Task

#273 Add JUnit tests
  src/main/java/seedu/address/logic/parser/FilterTasksCommandParser.java
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/logic/commands/FilterTasksCommandTest.java
  src/test/java/seedu/address/logic/parser/FilterTasksCommandParserTest.java
  src/test/java/seedu/address/model/task/FilterPredicateTest.java
  src/test/java/seedu/address/model/task/TaskLinkedToExamPredicateTest.java
Labels: type.Task

#289 Add tests for DistinctTaskList and Exam
  src/main/java/seedu/address/model/exam/Exam.java
  src/main/java/seedu/address/model/exam/exceptions/NoLinkedTaskForExamException.java
  src/main/java/seedu/address/model/task/DistinctTaskList.java
  src/test/data/JsonSerializableAddressBookTest/typicalTasksAddressBook.json
  src/test/java/seedu/address/model/exam/ExamTest.java
  src/test/java/seedu/address/model/task/DistinctTaskListTest.java
  src/test/java/seedu/address/testutil/ExamBuilder.java
  src/test/java/seedu/address/testutil/TypicalTasks.java
Labels: type.Task

#294 Fix bug regarding integer overflow
  src/main/java/seedu/address/commons/core/Messages.java
  src/main/java/seedu/address/logic/commands/EditTaskCommand.java
  src/main/java/seedu/address/logic/commands/MarkCommand.java
  src/main/java/seedu/address/logic/commands/UnmarkCommand.java
  src/main/java/seedu/address/logic/parser/EditTaskCommandParser.java
  src/main/java/seedu/address/logic/parser/MarkCommandParser.java
  src/main/java/seedu/address/logic/parser/UnmarkCommandParser.java
  src/test/java/seedu/address/logic/parser/EditTaskCommandParserTest.java
  src/test/java/seedu/address/logic/parser/MarkCommandParserTest.java
  src/test/java/seedu/address/logic/parser/UnmarkCommandParserTest.java
Labels: bug

#292 Add tests for AddressBook and DistinctExamList
  src/main/java/seedu/address/model/AddressBook.java
  src/main/java/seedu/address/model/exam/DistinctExamList.java
  src/main/java/seedu/address/model/module/Module.java
  src/test/java/seedu/address/model/AddressBookTest.java
  src/test/java/seedu/address/model/exam/DistinctExamListTest.java
Labels: type.Task

#301 Add tests for ModelManager class
  src/main/java/seedu/address/logic/commands/ClearAllCommand.java
  src/main/java/seedu/address/logic/commands/ClearTasksCommand.java
  src/main/java/seedu/address/model/ModelManager.java
  src/test/java/seedu/address/logic/commands/ClearAllCommandTest.java
  src/test/java/seedu/address/logic/commands/ClearTasksCommandTest.java
  src/test/java/seedu/address/logic/commands/DeleteExamCommandTest.java
  src/test/java/seedu/address/model/ModelManagerTest.java
  src/test/java/seedu/address/testutil/AddressBookBuilder.java
  src/test/java/seedu/address/testutil/TypicalExams.java
  src/test/java/seedu/address/testutil/TypicalTasks.java
Labels: type.Task

#309 Update front matters for ug
  docs/UserGuide.md
Labels: documentation

#302 Add tests for delete module/tasks command and command parser classes
  src/main/java/seedu/address/commons/core/Messages.java
  src/main/java/seedu/address/logic/commands/DeleteModuleCommand.java
  src/main/java/seedu/address/logic/commands/DeleteTaskCommand.java
  src/main/java/seedu/address/logic/parser/DeleteModuleCommandParser.java
  src/main/java/seedu/address/logic/parser/DeleteTaskCommandParser.java
  src/main/java/seedu/address/logic/parser/EditModuleCommandParser.java
  src/test/data/JsonSerializableAddressBookTest/typicalTasksAddressBook.json
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/logic/commands/DeleteModuleCommandTest.java
  src/test/java/seedu/address/logic/commands/DeleteTaskCommandTest.java
  src/test/java/seedu/address/logic/parser/DeleteModuleCommandParserTest.java
  src/test/java/seedu/address/logic/parser/DeleteTaskCommandParserTest.java
  src/test/java/seedu/address/model/exam/DistinctExamListTest.java
  src/test/java/seedu/address/testutil/TypicalExams.java
  src/test/java/seedu/address/testutil/TypicalIndexes.java
  src/test/java/seedu/address/testutil/TypicalModules.java
  src/test/java/seedu/address/testutil/TypicalTasks.java
Labels: priority.High

#296 Updated DG
  docs/DeveloperGuide.md
  docs/diagrams/ArchitectureSequenceDiagram.puml
  docs/diagrams/LinkExamCommandActivityDiagram.puml
  docs/diagrams/LinkExamCommandSequenceDiagram.puml
  docs/diagrams/ModelClassDiagram.puml
  docs/diagrams/SortTaskCommandActivityDiargam.puml
  docs/diagrams/SortTaskCommandSequenceDiagram.puml
  docs/diagrams/StorageClassDiagram.puml
  docs/diagrams/UiClassDiagram.puml
  docs/images/ArchitectureSequenceDiagram.png
  docs/images/LinkExamCommandActivityDiagram.png
  docs/images/LinkExamCommandSequenceDiagram.png
  docs/images/ModelClassDiagram.png
  docs/images/SortTaskCommandActivityDiagram.png
  docs/images/SortTaskCommandSequenceDiagram.png
  docs/images/StorageClassDiagram.png
  docs/images/UiClassDiagram.png
Labels: documentation

#307 Update dg final
  docs/DeveloperGuide.md
  docs/diagrams/AddExamActivityDiagram.puml
  docs/diagrams/AddExamCommandSequenceDiagram.puml
  docs/diagrams/FindTasksActivityDiagram.puml
  docs/diagrams/FindTasksCommandSequenceDiagram.puml
  docs/images/AddExamActivityDiagram.png
  docs/images/AddExamCommandSequenceDiagram.png
  docs/images/AddExamImage.png
  docs/images/FindCommandImage.png
  docs/images/FindTasksActivityDiagram.png
  docs/images/FindTasksCommandSequenceDiagram.png
Labels: documentation

#313 Update mark task, unmark task and edit task features in UG
  docs/UserGuide.md
  docs/images/MarkTask.png
Labels: documentation

#306 Fix integer issue
  src/main/java/seedu/address/commons/core/Messages.java
  src/main/java/seedu/address/logic/parser/EditExamCommandParser.java
  src/test/java/seedu/address/logic/parser/EditExamCommandParserTest.java
Labels: bug

#314 Update ug final
  docs/UserGuide.md
  docs/images/FindCommandImage.png
Labels: documentation

#305 Fix integer overflow bug
  src/main/java/seedu/address/commons/core/Messages.java
  src/main/java/seedu/address/logic/commands/DeleteExamCommand.java
  src/main/java/seedu/address/logic/commands/ListExamTasksCommand.java
  src/main/java/seedu/address/logic/commands/UnlinkExamCommand.java
  src/main/java/seedu/address/logic/parser/DeleteExamCommandParser.java
  src/main/java/seedu/address/logic/parser/ListExamTasksCommandParser.java
  src/main/java/seedu/address/logic/parser/UnlinkExamCommandParser.java
  src/test/java/seedu/address/logic/commands/DeleteExamCommandTest.java
  src/test/java/seedu/address/logic/commands/ListExamTasksCommandTest.java
  src/test/java/seedu/address/logic/commands/UnlinkExamCommandTest.java
  src/test/java/seedu/address/logic/parser/DeleteExamCommandParserTest.java
  src/test/java/seedu/address/logic/parser/ListExamTasksCommandParserTest.java
  src/test/java/seedu/address/logic/parser/UnlinkExamCommandParserTest.java
Labels: bug

#319 Update DG
  docs/DeveloperGuide.md
  docs/diagrams/FilterActivityDiagram.puml
  docs/diagrams/FilterSequenceDiagram.puml
  docs/diagrams/UnlinkExamActivityDiagram.puml
  docs/diagrams/UnlinkExamSequenceDiagram.puml
  docs/images/FilterActivityDiagram.png
  docs/images/FilterSequenceDiagram.png
  docs/images/UnlinkExamActivityDiagram.png
  docs/images/UnlinkExamSequenceDiagram.png
Labels: documentation

#321 Update deleteModule, deleteTask and editModule in UG
  docs/UserGuide.md
Labels: documentation

#316 Update UG features
  docs/UserGuide.md
  docs/images/AddModuleCommandDemo.png
  docs/images/AddTagCommandDemo.png
  docs/images/GUI.png
  docs/images/LinkExamCommandDemo.png
  docs/images/SortTaskCommandDemo.png
Labels: documentation

#325 Update UG
  docs/UserGuide.md
  docs/images/AddTaskCommandDemo.png
  docs/images/FilterTasksCommandDemo.png
  docs/images/ListExamTasksCommandDemo.png
Labels: documentation

#327 Fix empty description error
  src/main/java/seedu/address/model/exam/ExamDescription.java
  src/main/java/seedu/address/model/module/ModuleName.java
  src/main/java/seedu/address/model/task/TaskDescription.java
Labels: bug

#329 Update PPP
  docs/team/phualiting.md
Labels: documentation
