Repository AY2223S1-CS2103T-F11-2/tp, pull requests merged in 2022-10, with the labels that each got.

#49 Add Module class and AddModuleCommand class
  src/main/java/seedu/address/logic/Logic.java
  src/main/java/seedu/address/logic/LogicManager.java
  src/main/java/seedu/address/logic/commands/AddModuleCommand.java
  src/main/java/seedu/address/logic/parser/AddModuleCommandParser.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/logic/parser/CliSyntax.java
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/main/java/seedu/address/model/AddressBook.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/model/ReadOnlyAddressBook.java
  src/main/java/seedu/address/model/module/DistinctModuleList.java
  src/main/java/seedu/address/model/module/Module.java
  src/main/java/seedu/address/model/module/ModuleCode.java
  src/main/java/seedu/address/model/module/exceptions/DuplicateModuleException.java
  src/main/java/seedu/address/storage/JsonAdaptedModule.java
  src/main/java/seedu/address/storage/JsonAdaptedTask.java
  src/main/java/seedu/address/storage/JsonSerializableAddressBook.java
  src/main/java/seedu/address/ui/MainWindow.java
  src/main/java/seedu/address/ui/ModuleCard.java
  src/main/java/seedu/address/ui/ModuleListPanel.java
  src/main/resources/view/MainWindow.fxml
  src/main/resources/view/ModuleListCard.fxml
  src/main/resources/view/ModuleListPanel.fxml
  src/test/data/JsonAddressBookStorageTest/invalidAndValidPersonAddressBook.json
  src/test/data/JsonAddressBookStorageTest/invalidPersonAddressBook.json
  src/test/data/JsonSerializableAddressBookTest/duplicatePersonAddressBook.json
  src/test/data/JsonSerializableAddressBookTest/invalidPersonAddressBook.json
  src/test/data/JsonSerializableAddressBookTest/typicalPersonsAddressBook.json
  src/test/java/seedu/address/logic/commands/AddCommandTest.java
  src/test/java/seedu/address/model/AddressBookTest.java
Labels: enhancement, priority.High

#51 Add Task class and update classes in storage
  src/main/java/seedu/address/logic/Logic.java
  src/main/java/seedu/address/logic/LogicManager.java
  src/main/java/seedu/address/model/AddressBook.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/model/ReadOnlyAddressBook.java
  src/main/java/seedu/address/model/task/DistinctTaskList.java
  src/main/java/seedu/address/model/task/Task.java
  src/main/java/seedu/address/model/task/TaskDescription.java
  src/main/java/seedu/address/storage/JsonAdaptedTask.java
  src/main/java/seedu/address/storage/JsonSerializableAddressBook.java
  src/main/java/seedu/address/ui/MainWindow.java
  src/main/java/seedu/address/ui/TaskCard.java
  src/main/java/seedu/address/ui/TaskListPanel.java
  src/main/resources/view/MainWindow.fxml
  src/main/resources/view/TaskListCard.fxml
  src/main/resources/view/TaskListPanel.fxml
  src/test/java/seedu/address/logic/commands/AddCommandIntegrationTest.java
  src/test/java/seedu/address/logic/commands/AddCommandTest.java
  src/test/java/seedu/address/logic/commands/DeleteCommandTest.java
  src/test/java/seedu/address/logic/commands/EditCommandTest.java
  src/test/java/seedu/address/logic/commands/FindCommandTest.java
  src/test/java/seedu/address/logic/commands/ListCommandTest.java
  src/test/java/seedu/address/model/AddressBookTest.java
  src/test/java/seedu/address/model/ModelManagerTest.java
  src/test/java/seedu/address/storage/JsonAddressBookStorageTest.java
  src/test/java/seedu/address/storage/JsonSerializableAddressBookTest.java
  src/test/java/seedu/address/storage/StorageManagerTest.java
Labels: enhancement, priority.High, type.Task

#52 Add create tasks feature
  src/main/java/seedu/address/logic/commands/TaskCommand.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/logic/parser/CliSyntax.java
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/main/java/seedu/address/logic/parser/TaskCommandParser.java
  src/main/java/seedu/address/model/AddressBook.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/model/ReadOnlyAddressBook.java
  src/main/java/seedu/address/model/module/Module.java
  src/main/java/seedu/address/model/task/DistinctTaskList.java
  src/main/java/seedu/address/model/task/Task.java
  src/main/java/seedu/address/model/task/TaskModule.java
  src/main/java/seedu/address/model/task/exceptions/DuplicateTaskException.java
  src/test/java/seedu/address/logic/LogicManagerTest.java
  src/test/java/seedu/address/logic/commands/AddCommandIntegrationTest.java
  src/test/java/seedu/address/logic/commands/AddCommandTest.java
  src/test/java/seedu/address/logic/commands/ClearCommandTest.java
  src/test/java/seedu/address/logic/commands/ExitCommandTest.java
  src/test/java/seedu/address/logic/commands/FindCommandTest.java
  src/test/java/seedu/address/logic/commands/HelpCommandTest.java
  src/test/java/seedu/address/logic/commands/ListCommandTest.java
  src/test/java/seedu/address/model/AddressBookTest.java
Labels: enhancement, priority.High, type.Task

#53 Add ListTasks and FindTasks commands
  src/main/java/seedu/address/commons/core/Messages.java
  src/main/java/seedu/address/logic/commands/FindTasksCommand.java
  src/main/java/seedu/address/logic/commands/ListTasksCommand.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/logic/parser/FindTaskCommandParser.java
  src/main/java/seedu/address/model/AddressBook.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/model/task/DescriptionContainsKeywordsPredicate.java
  src/main/java/seedu/address/model/task/DistinctTaskList.java
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/logic/commands/FindCommandTest.java
  src/test/java/seedu/address/logic/commands/FindTasksCommandTest.java
  src/test/java/seedu/address/logic/commands/ListTasksCommandTest.java
Labels: enhancement, priority.High, type.Task

#59 Add filter tasks by module and completion status
  src/main/java/seedu/address/commons/core/Messages.java
  src/main/java/seedu/address/logic/commands/AddTaskCommand.java
  src/main/java/seedu/address/logic/commands/FilterTasksCommand.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/logic/parser/CliSyntax.java
  src/main/java/seedu/address/logic/parser/FilterTasksCommandParser.java
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/main/java/seedu/address/model/task/FilterPredicate.java
  src/main/java/seedu/address/model/task/TaskModule.java
Labels: enhancement, type.Task

#61 Add tagging feature for task
  src/main/java/seedu/address/logic/commands/AddModuleCommand.java
  src/main/java/seedu/address/logic/commands/AddTagCommand.java
  src/main/java/seedu/address/logic/parser/AddTagCommandParser.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/logic/parser/CliSyntax.java
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/main/java/seedu/address/model/tag/PriorityTag.java
  src/main/java/seedu/address/model/tag/exceptions/PriorityTagAlreadyExistsException.java
  src/main/java/seedu/address/model/task/Task.java
  src/main/java/seedu/address/storage/JsonAdaptedTask.java
  src/main/java/seedu/address/ui/TaskCard.java
  src/main/resources/view/ModuleListCard.fxml
  src/main/resources/view/TaskListCard.fxml
Labels: enhancement, priority.High

#63 Add clear tasks and clear modules commands
  src/main/java/seedu/address/commons/core/Messages.java
  src/main/java/seedu/address/logic/commands/ClearModulesCommand.java
  src/main/java/seedu/address/logic/commands/ClearTasksCommand.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
Labels: enhancement, type.Task

#66 Update FindTask command to work for partial keyword.
  src/main/java/seedu/address/commons/util/StringUtil.java
  src/main/java/seedu/address/logic/Logic.java
  src/main/java/seedu/address/logic/commands/FindTasksCommand.java
  src/main/java/seedu/address/logic/commands/ListTasksCommand.java
  src/main/java/seedu/address/logic/parser/FindTaskCommandParser.java
  src/main/java/seedu/address/model/task/DescriptionContainsKeywordsPredicate.java
Labels: enhancement

#68 Find modules and List modules command
  src/main/java/seedu/address/commons/core/Messages.java
  src/main/java/seedu/address/commons/util/StringUtil.java
  src/main/java/seedu/address/logic/Logic.java
  src/main/java/seedu/address/logic/LogicManager.java
  src/main/java/seedu/address/logic/commands/FindModulesCommand.java
  src/main/java/seedu/address/logic/commands/FindTasksCommand.java
  src/main/java/seedu/address/logic/commands/ListModulesCommand.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/logic/parser/FindModulesCommandParser.java
  src/main/java/seedu/address/logic/parser/FindTaskCommandParser.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/model/module/ModuleCodeContainsKeywordsPredicate.java
  src/main/java/seedu/address/ui/MainWindow.java
  src/main/java/seedu/address/ui/TaskListPanel.java
  src/test/java/seedu/address/logic/commands/AddCommandTest.java
Labels: enhancement

#76 Change isSameModuleCode method name to isSameModule
  src/main/java/seedu/address/commons/core/Messages.java
  src/main/java/seedu/address/logic/commands/EditModuleCommand.java
  src/main/java/seedu/address/model/module/DistinctModuleList.java
  src/main/java/seedu/address/model/module/Module.java
  src/main/java/seedu/address/model/task/DistinctTaskList.java
Labels: priority.Medium

#86 Remove redundant TaskModule class
  src/main/java/seedu/address/logic/parser/AddTaskCommandParser.java
  src/main/java/seedu/address/logic/parser/FilterTasksCommandParser.java
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/main/java/seedu/address/model/task/TaskModule.java
Labels: type.Task

#84 Add Exam class and AddExamCommand class
  src/main/java/seedu/address/commons/core/Messages.java
  src/main/java/seedu/address/logic/Logic.java
  src/main/java/seedu/address/logic/LogicManager.java
  src/main/java/seedu/address/logic/commands/AddExamCommand.java
  src/main/java/seedu/address/logic/parser/AddExamCommandParser.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/logic/parser/CliSyntax.java
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/main/java/seedu/address/model/AddressBook.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/model/ReadOnlyAddressBook.java
  src/main/java/seedu/address/model/exam/DistinctExamList.java
  src/main/java/seedu/address/model/exam/Exam.java
  src/main/java/seedu/address/model/exam/ExamDate.java
  src/main/java/seedu/address/model/exam/ExamDescription.java
  src/main/java/seedu/address/model/exam/exceptions/DuplicateExamException.java
  src/main/java/seedu/address/model/exam/exceptions/ExamIdentityModifiedException.java
  src/main/java/seedu/address/model/exam/exceptions/ExamNotFoundException.java
  src/main/java/seedu/address/storage/JsonAdaptedExam.java
  src/main/java/seedu/address/storage/JsonSerializableAddressBook.java
  src/main/java/seedu/address/ui/ExamCard.java
  src/main/java/seedu/address/ui/ExamListPanel.java
  src/main/java/seedu/address/ui/MainWindow.java
  src/main/resources/view/ExamListCard.fxml
  src/main/resources/view/ExamListPanel.fxml
  src/main/resources/view/MainWindow.fxml
  src/test/java/seedu/address/logic/commands/AddCommandTest.java
  src/test/java/seedu/address/model/AddressBookTest.java
Labels: type.Task

#90 Fix bugs
  src/main/java/seedu/address/logic/commands/AddTagCommand.java
  src/main/java/seedu/address/logic/commands/EditTaskCommand.java
  src/main/java/seedu/address/logic/commands/MarkCommand.java
  src/main/java/seedu/address/logic/commands/UnmarkCommand.java
  src/main/java/seedu/address/model/AddressBook.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/model/task/DistinctTaskList.java
  src/main/java/seedu/address/model/task/exceptions/TaskIdentityModifiedException.java
  src/main/java/seedu/address/model/task/exceptions/WrongTaskModifiedException.java
  src/test/java/seedu/address/logic/commands/AddCommandTest.java
Labels: bug

#106 Update DG with Delete Module and Edit Module features
  docs/DeveloperGuide.md
Labels: documentation, priority.High

#107 Add sort feature implementation in DG
  docs/DeveloperGuide.md
  docs/diagrams/SortTaskCommandSequenceDiagram.puml
  docs/images/SortTaskCommandSequenceDiagram.png
Labels: documentation

#110 Update DG with filter implementation
  docs/DeveloperGuide.md
  docs/diagrams/FilterActivityDiagram.puml
  docs/diagrams/FilterSequenceDiagram.puml
  docs/images/FilterActivityDiagram.png
  docs/images/FilterSequenceDiagram.png
Labels: documentation, priority.High

#112 Update developer guide for the mark task feature
  docs/DeveloperGuide.md
  docs/diagrams/MarkTaskActivityDiagram.puml
  docs/diagrams/MarkTaskSequenceDiagram.puml
  docs/images/MarkTaskActivityDiagram.png
  docs/images/MarkTaskSequenceDiagram.png
Labels: documentation, priority.High

#92 Add sorting feature
  src/main/java/seedu/address/logic/commands/SortTaskCommand.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/logic/parser/CliSyntax.java
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/main/java/seedu/address/logic/parser/SortTaskCommandParser.java
  src/main/java/seedu/address/model/AddressBook.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/model/commons/Criteria.java
  src/main/java/seedu/address/model/module/Module.java
  src/main/java/seedu/address/model/tag/DeadlineTag.java
  src/main/java/seedu/address/model/tag/PriorityTag.java
  src/main/java/seedu/address/model/task/DistinctTaskList.java
  src/main/java/seedu/address/model/task/TaskDescription.java
  src/test/java/seedu/address/logic/commands/AddCommandTest.java
Labels: enhancement, priority.Medium

#99 Add progress bar for each module
  src/main/java/seedu/address/model/AddressBook.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/model/module/DistinctModuleList.java
  src/main/java/seedu/address/model/module/Module.java
  src/main/java/seedu/address/model/task/DistinctTaskList.java
  src/main/java/seedu/address/ui/ModuleCard.java
  src/main/resources/view/ModuleListCard.fxml
Labels: enhancement, priority.Medium

#104 Add link exam feature
  build.gradle
  src/main/java/seedu/address/commons/core/Messages.java
  src/main/java/seedu/address/logic/commands/LinkExamCommand.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/logic/parser/CliSyntax.java
  src/main/java/seedu/address/logic/parser/LinkExamCommandParser.java
  src/main/java/seedu/address/model/AddressBook.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/model/exam/DistinctExamList.java
  src/main/java/seedu/address/model/exam/Exam.java
  src/main/java/seedu/address/model/exam/ExamDate.java
  src/main/java/seedu/address/model/module/Module.java
  src/main/java/seedu/address/model/task/Task.java
  src/main/java/seedu/address/storage/JsonAdaptedExam.java
  src/main/java/seedu/address/storage/JsonAdaptedTask.java
  src/main/java/seedu/address/storage/JsonSerializableAddressBook.java
  src/main/java/seedu/address/ui/TaskCard.java
  src/main/resources/view/TaskListCard.fxml
  src/test/java/seedu/address/logic/commands/AddCommandTest.java
Labels: enhancement, priority.High

#117 Add listexamtasks command
  src/main/java/seedu/address/logic/commands/ListExamTasksCommand.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/logic/parser/ListExamTasksCommandParser.java
  src/main/java/seedu/address/model/task/TaskLinkedToExamPredicate.java
Labels: enhancement, priority.Medium, type.Task

#120 Add unlink exam feature
  src/main/java/seedu/address/logic/commands/UnlinkExamCommand.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/logic/parser/UnlinkExamCommandParser.java
  src/main/java/seedu/address/model/task/Task.java
Labels: enhancement, priority.Medium, type.Task

#134 Add delete exam feature
  src/main/java/seedu/address/logic/commands/DeleteExamCommand.java
  src/main/java/seedu/address/logic/commands/DeleteModuleCommand.java
  src/main/java/seedu/address/logic/commands/DeleteTaskCommand.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/logic/parser/DeleteExamCommandParser.java
  src/main/java/seedu/address/model/AddressBook.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/model/task/DistinctTaskList.java
  src/test/java/seedu/address/logic/commands/AddCommandTest.java
Labels: enhancement, priority.High

#121 Adding new fields to module class
  src/main/java/seedu/address/logic/commands/AddModuleCommand.java
  src/main/java/seedu/address/logic/commands/AddTaskCommand.java
  src/main/java/seedu/address/logic/commands/EditModuleCommand.java
  src/main/java/seedu/address/logic/parser/AddModuleCommandParser.java
  src/main/java/seedu/address/logic/parser/AddTaskCommandParser.java
  src/main/java/seedu/address/logic/parser/CliSyntax.java
  src/main/java/seedu/address/logic/parser/EditModuleCommandParser.java
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/main/java/seedu/address/model/module/DistinctModuleList.java
  src/main/java/seedu/address/model/module/Module.java
  src/main/java/seedu/address/model/module/ModuleCredit.java
  src/main/java/seedu/address/model/module/ModuleName.java
  src/main/java/seedu/address/model/module/exceptions/NullModuleCodeException.java
  src/main/java/seedu/address/storage/JsonAdaptedModule.java
  src/main/java/seedu/address/ui/ModuleCard.java
  src/main/resources/view/ModuleListCard.fxml
Labels: priority.High

#137 Update filter feature to support filter by link status and shorten input commands to y/n
  src/main/java/seedu/address/logic/commands/FilterTasksCommand.java
  src/main/java/seedu/address/logic/parser/CliSyntax.java
  src/main/java/seedu/address/logic/parser/FilterTasksCommandParser.java
  src/main/java/seedu/address/model/task/FilterPredicate.java
Labels: enhancement, priority.Medium

#142 Add edit exam command
  src/main/java/seedu/address/logic/commands/EditExamCommand.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/logic/parser/EditExamCommandParser.java
  src/main/java/seedu/address/model/AddressBook.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/model/exam/Exam.java
  src/main/java/seedu/address/model/task/DistinctTaskList.java
  src/test/java/seedu/address/logic/commands/AddCommandTest.java
Labels: enhancement

#130 Add progress bar for exams
  src/main/java/seedu/address/logic/commands/LinkExamCommand.java
  src/main/java/seedu/address/model/AddressBook.java
  src/main/java/seedu/address/model/exam/DistinctExamList.java
  src/main/java/seedu/address/model/exam/Exam.java
  src/main/java/seedu/address/model/module/DistinctModuleList.java
  src/main/java/seedu/address/model/task/DistinctTaskList.java
  src/main/java/seedu/address/model/task/Task.java
  src/main/java/seedu/address/storage/JsonSerializableAddressBook.java
  src/main/java/seedu/address/ui/ExamCard.java
  src/main/resources/view/ExamListCard.fxml
Labels: enhancement, priority.Medium

#154 Update help window
  src/main/java/seedu/address/ui/HelpWindow.java
  src/main/resources/view/HelpWindow.css
  src/main/resources/view/HelpWindow.fxml
  src/main/resources/view/MainWindow.fxml
Labels: priority.High, type.Task

#147 Change clearmodules to clearall and fix cleartasks progress bar bug
  src/main/java/seedu/address/commons/core/Messages.java
  src/main/java/seedu/address/logic/commands/ClearAllCommand.java
  src/main/java/seedu/address/logic/commands/ClearTasksCommand.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/model/AddressBook.java
  src/main/java/seedu/address/model/exam/DistinctExamList.java
  src/main/java/seedu/address/model/module/DistinctModuleList.java
Labels: priority.Medium

#165 Update user guide
  docs/UserGuide.md
Labels: documentation

#168 Modify list panels and overall app layout UI
  src/main/resources/view/DarkTheme.css
  src/main/resources/view/ExamListPanel.fxml
  src/main/resources/view/MainWindow.fxml
  src/main/resources/view/ModuleListPanel.fxml
  src/main/resources/view/TaskListPanel.fxml
Labels: priority.Medium

#157 Update the GUI for task card
  src/main/java/seedu/address/ui/TaskCard.java
  src/main/resources/view/DarkTheme.css
  src/main/resources/view/TaskListCard.fxml
Labels: enhancement, priority.Medium

#149 Update Edit Module feature
  src/main/java/seedu/address/commons/util/CollectionUtil.java
  src/main/java/seedu/address/logic/commands/EditModuleCommand.java
  src/main/java/seedu/address/model/AddressBook.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/model/exam/DistinctExamList.java
  src/main/java/seedu/address/model/exam/Exam.java
  src/main/java/seedu/address/model/task/DistinctTaskList.java
  src/main/java/seedu/address/model/task/Task.java
  src/test/java/seedu/address/logic/commands/AddCommandTest.java
Labels: priority.Medium

#161 Update command formats
  src/main/java/seedu/address/commons/core/Messages.java
  src/main/java/seedu/address/logic/commands/AddExamCommand.java
  src/main/java/seedu/address/logic/commands/AddModuleCommand.java
  src/main/java/seedu/address/logic/commands/AddTagCommand.java
  src/main/java/seedu/address/logic/commands/AddTaskCommand.java
  src/main/java/seedu/address/logic/commands/ClearTasksCommand.java
  src/main/java/seedu/address/logic/commands/DeleteCommand.java
  src/main/java/seedu/address/logic/commands/DeleteExamCommand.java
  src/main/java/seedu/address/logic/commands/DeleteModuleCommand.java
  src/main/java/seedu/address/logic/commands/DeleteTagCommand.java
  src/main/java/seedu/address/logic/commands/DeleteTaskCommand.java
  src/main/java/seedu/address/logic/commands/EditExamCommand.java
  src/main/java/seedu/address/logic/commands/EditModuleCommand.java
  src/main/java/seedu/address/logic/commands/EditTagCommand.java
  src/main/java/seedu/address/logic/commands/EditTaskCommand.java
  src/main/java/seedu/address/logic/commands/FindModulesCommand.java
  src/main/java/seedu/address/logic/commands/FindTasksCommand.java
  src/main/java/seedu/address/logic/commands/LinkExamCommand.java
  src/main/java/seedu/address/logic/commands/ListExamTasksCommand.java
  src/main/java/seedu/address/logic/commands/ListModulesCommand.java
  src/main/java/seedu/address/logic/commands/ListTasksCommand.java
  src/main/java/seedu/address/logic/commands/UnlinkExamCommand.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/test/java/seedu/address/logic/LogicManagerTest.java
  src/test/java/seedu/address/logic/parser/AddressBookParserTest.java
Labels: priority.High, type.Task

#179 Fix bug regarding the checkbox and update error messages to be more specific
  src/main/java/seedu/address/commons/core/Messages.java
  src/main/java/seedu/address/logic/commands/EditTaskCommand.java
  src/main/java/seedu/address/logic/commands/MarkCommand.java
  src/main/java/seedu/address/logic/commands/UnmarkCommand.java
  src/main/java/seedu/address/logic/parser/EditTaskCommandParser.java
  src/main/java/seedu/address/logic/parser/MarkCommandParser.java
  src/main/java/seedu/address/logic/parser/UnmarkCommandParser.java
  src/main/java/seedu/address/model/task/Task.java
  src/main/java/seedu/address/storage/JsonAdaptedTask.java
  src/main/resources/view/DarkTheme.css
  src/main/resources/view/TaskListCard.fxml
Labels: bug

#177 Update user guide
  docs/UserGuide.md
Labels: documentation

#187 Update user guide
  docs/UserGuide.md
Labels: documentation

#176 Update GUI for list containers
  src/main/java/seedu/address/ui/ExamCard.java
  src/main/java/seedu/address/ui/TaskCard.java
  src/main/resources/view/DarkTheme.css
  src/main/resources/view/ExamListCard.fxml
  src/main/resources/view/HelpWindow.fxml
  src/main/resources/view/MainWindow.fxml
  src/main/resources/view/ModuleListCard.fxml
  src/main/resources/view/TaskListCard.fxml
Labels: bug, type.Task

#192 Update userguide and javadocs to include DD-MM-YYYY and specification
  docs/UserGuide.md
  src/main/java/seedu/address/model/exam/ExamDate.java
Labels: documentation

#181 Update to handle case where list is empty
  src/main/java/seedu/address/logic/commands/SortTaskCommand.java
Labels: bug

#190 Add more exception messages for different indexes
  src/main/java/seedu/address/logic/parser/LinkExamCommandParser.java
Labels: type.Task

#186 Update deadline exception messages
  src/main/java/seedu/address/logic/commands/AddModuleCommand.java
  src/main/java/seedu/address/logic/commands/AddTagCommand.java
  src/main/java/seedu/address/logic/commands/DeleteTagCommand.java
  src/main/java/seedu/address/logic/commands/EditTagCommand.java
  src/main/java/seedu/address/logic/commands/LinkExamCommand.java
  src/main/java/seedu/address/logic/commands/SortTaskCommand.java
  src/main/java/seedu/address/logic/parser/AddTagCommandParser.java
  src/main/java/seedu/address/logic/parser/EditTagCommandParser.java
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/main/java/seedu/address/model/tag/DeadlineTag.java
  src/main/java/seedu/address/storage/JsonAdaptedTask.java
Labels: type.Task

#194 Update user guide
  docs/UserGuide.md
Labels: documentation

#195 Update user guide
  docs/UserGuide.md
Labels: documentation

#174 Update to detect whitespace characters
  src/main/java/seedu/address/logic/parser/ParserUtil.java
Labels: bug

#198 Update name of json file
  src/main/java/seedu/address/model/UserPrefs.java
Labels: type.Task

#183 Modify edit module feature
  src/main/java/seedu/address/commons/core/Messages.java
  src/main/java/seedu/address/logic/commands/AddModuleCommand.java
  src/main/java/seedu/address/logic/commands/EditModuleCommand.java
  src/main/java/seedu/address/logic/parser/EditModuleCommandParser.java
  src/main/java/seedu/address/model/module/ModuleName.java
Labels: priority.High

#200 Update Edit Task feature with more guiding messages for the user
  src/main/java/seedu/address/logic/commands/DeleteTaskCommand.java
  src/main/java/seedu/address/logic/parser/DeleteTaskCommandParser.java
Labels: priority.Medium

#201 Update UG with delete, edit module and edit task features
  docs/UserGuide.md
Labels: priority.Medium

#202 Make final changes
  docs/UserGuide.md
  docs/images/Ui.png
  src/main/java/seedu/address/logic/commands/AddModuleCommand.java
  src/main/java/seedu/address/logic/commands/AddTagCommand.java
  src/main/java/seedu/address/logic/commands/DeleteExamCommand.java
  src/main/java/seedu/address/logic/commands/DeleteModuleCommand.java
  src/main/java/seedu/address/logic/commands/DeleteTagCommand.java
  src/main/java/seedu/address/logic/commands/DeleteTaskCommand.java
  src/main/java/seedu/address/logic/commands/EditExamCommand.java
  src/main/java/seedu/address/logic/commands/EditModuleCommand.java
  src/main/java/seedu/address/logic/commands/EditTagCommand.java
  src/main/java/seedu/address/logic/commands/EditTaskCommand.java
  src/main/java/seedu/address/logic/commands/LinkExamCommand.java
  src/main/java/seedu/address/logic/commands/ListExamTasksCommand.java
  src/main/java/seedu/address/logic/commands/MarkCommand.java
  src/main/java/seedu/address/logic/commands/SortTaskCommand.java
  src/main/java/seedu/address/logic/commands/UnlinkExamCommand.java
  src/main/java/seedu/address/logic/commands/UnmarkCommand.java
  src/main/java/seedu/address/model/module/ModuleCode.java
  src/main/java/seedu/address/model/module/ModuleCredit.java
  src/main/resources/view/HelpWindow.fxml
Labels: type.Task

#249 Add JUnit tests for AddTaskCommand and AddTaskCommandParser classes
  src/test/java/seedu/address/logic/commands/AddTaskCommandTest.java
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/logic/parser/AddTaskCommandParserTest.java
  src/test/java/seedu/address/testutil/TaskBuilder.java
  src/test/java/seedu/address/testutil/TypicalTasks.java
Labels: type.Task
